[package]
name = "keylogger-cool"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
parking_lot = "0.12.1"
sqlite = "0.32.0"

[build-dependencies]
cc = "1.0.83"
