[package]
name = "keylogger-cool"
description = "An ethical keylogger for science."
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
parking_lot = "0.12.1"
rusqlite = { version = "0.30.0", features = ["bundled"] }

[build-dependencies]
cc = "1.0.83"

[package.metadata.bundle]
name = "keylogger.cool"
identifier = "dev.malted.keylogger"
# icon = ["32x32.png", "128x128.png", "128x128@2x.png"]
version = "1.0.0"
# resources = ["assets", "images/**/*.png", "secrets/public_key.txt"]
copyright = "Copyright (c) Malted 2023. All rights reserved."
category = "Productivity"
short_description = "An ethical keylogger for science."
