[package]
name = "delegate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
once_cell = "1.18.0"
parking_lot = "0.12.1"
serde_json = "1.0.103"
tungstenite = { version = "0.19.0", features = ["native-tls"] }
